"""Alembic database migration configuration"""

from alembic import op
import sqlalchemy as sa


def upgrade():
    """Create initial tables"""
    # This will be auto-generated by alembic
    pass


def downgrade():
    """Drop tables"""
    pass
